notifications:
  email: false

language: cpp

sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

    - os: windows
      compiler: clang

#    - os: windows
#      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#
#    - os: windows
#      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh


before_script:
  - source ci/travis/configure-$TRAVIS_OS_NAME.sh

script:
  - source ci/travis/build-$TRAVIS_OS_NAME.sh

after_success:
  - cd ./build
  - ctest --output-on-failure
  - if [[ "$TRAVIS_OS_NAME" != "windows" && "$BUILD_CONFIGURATION" == "Release" ]]; then cpack; fi

deploy:
  - provider: releases
    api_key:
      secure: YBXTJxTn9ztZSGEX830or/qaaJ64RnoAxetM1Ujy10Segf6ztDOnn+/S05B5PUqQMKaejT7gdKvGryLqtQD69O7QHbNx5SWK5HEC5SVmEdrF37+xPNTM99g3C4VQ8Nq1yf74cdzRYwPiz/bsN0OsiV9Xz/k3GxeDKt6NRJE9FpxVS2aeIwxurPhb5PlAP/Yp+61x8DNMepgCMXkddqVTgEUPGT1iW2wPuxaKObMnElarodjFWgNmU/zoo+qCCOs+TwaavKu9Q+YUaX20U6ZxvRg3vOJ4w1kBa3mMRTs9fR78ZkO8erEIqF1S54LmMQDxg4vMdeziQ0jkLmiRNV5xc3nnyh4sruiA15qH1jirLMV5m8+eZRr4L9P0d9n817a3HQYk5DKs4cg0RI+7Ygh7fRrbHwSoMFY8hp7QVnw1ae+00nFgA7dHBc9CyUPCHC/+wBCP7ZU9pAOL+wkPQjeUjeN9kvKDeoo/S+Veamiqs55XQXNht44HVNevdcTJhjhJNDAxWwDG2OFMiyXxBArFAN4DQqhFzo8L4FrZibo731SzWL3O8qs58QQQT0XAQ/kwAdUfG8qSKNEagcvX4KiHNqPBZXt8vCC/CZhb7QT0rjLoewJQC62YylfBl45L0UP5rHNS6kpZhoX87A9EouKt7ubCai11xwlCIZkm93UIQxw=
    file_glob: true
    file:
      - $TRAVIS_BUILD_DIR/build/wav_revival*.sh
      - $TRAVIS_BUILD_DIR/build/wav_revival*.tar.gz
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: ($TRAVIS_OS_NAME = "linux" || $TRAVIS_OS_NAME = "osx") && $BUILD_CONFIGURATION = "Release"
